[package]
name = "xtask"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "blocking", "rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = "1"
zip = "2"

[[bin]]
name = "xtask"
path = "src/main.rs"
