//! Register built-in API providers and default models.
//!
//! Model data is generated at build time by build.rs (which fetches from
//! provider model list APIs, matching the original pi generate-models.ts logic).

use std::collections::HashMap;
use std::sync::Arc;

use crate::api_registry::{clear_api_providers, register_api_provider, ApiProvider};
use crate::providers::anthropic::{stream_anthropic, stream_simple_anthropic};
use crate::providers::openai::{stream_openai, stream_simple_openai};
use crate::types::Model;

/// Register all built-in API providers and default models.
pub fn register_built_in_api_providers() {
    load_generated_models();

    register_api_provider(
        ApiProvider {
            api: "anthropic-messages".to_string(),
            stream: Arc::new(move |model, context, options| {
                stream_anthropic(model, context, options)
            }),
            stream_simple: Arc::new(move |model, context, options| {
                stream_simple_anthropic(model, context, options)
            }),
        },
        Some("builtin"),
    );

    register_api_provider(
        ApiProvider {
            api: "openai-completions".to_string(),
            stream: Arc::new(move |model, context, options| stream_openai(model, context, options)),
            stream_simple: Arc::new(move |model, context, options| {
                stream_simple_openai(model, context, options)
            }),
        },
        Some("builtin"),
    );

    // Mistral uses OpenAI-compatible format
    register_api_provider(
        ApiProvider {
            api: "mistral-conversations".to_string(),
            stream: Arc::new(move |model, context, options| stream_openai(model, context, options)),
            stream_simple: Arc::new(move |model, context, options| {
                stream_simple_openai(model, context, options)
            }),
        },
        Some("builtin"),
    );
}

/// Clear all providers and re-register the built-in ones.
pub fn reset_api_providers() {
    clear_api_providers();
    register_built_in_api_providers();
}

/// Load models generated by build.rs, embedded at compile time.
fn load_generated_models() {
    let json = include_str!(concat!(env!("OUT_DIR"), "/models_generated.json"));
    match serde_json::from_str::<HashMap<String, HashMap<String, Model>>>(json) {
        Ok(by_provider) => {
            for (_, models) in by_provider {
                for (_, model) in models {
                    crate::models::register_model(model);
                }
            }
        }
        Err(e) => {
            println!("cargo:warning=Failed to parse generated models: {}", e);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api_registry::get_api_provider;

    #[test]
    fn test_register_builtins_registers_anthropic() {
        register_built_in_api_providers();
        assert!(get_api_provider("anthropic-messages").is_some());
    }

    #[test]
    fn test_register_builtins_registers_openai() {
        register_built_in_api_providers();
        assert!(get_api_provider("openai-completions").is_some());
    }

    #[test]
    fn test_register_builtins_registers_mistral() {
        register_built_in_api_providers();
        assert!(get_api_provider("mistral-conversations").is_some());
    }

    #[test]
    fn test_reset_api_providers() {
        reset_api_providers();
        assert!(get_api_provider("anthropic-messages").is_some());
        assert!(get_api_provider("openai-completions").is_some());
    }

    #[test]
    fn test_unknown_provider_returns_none() {
        register_built_in_api_providers();
        assert!(get_api_provider("unknown-api").is_none());
    }

    #[test]
    fn test_loads_generated_models() {
        register_built_in_api_providers();
        let providers = crate::models::get_providers();
        assert!(
            !providers.is_empty(),
            "Expected at least one provider from generated models, got none."
        );
    }
}
