//! Register built-in API providers and default models.
//!
//! Model data is generated by `cargo run -p xtask -- generate-models` (port of
//! pi's `scripts/generate-models.ts`), committed to `data/models_generated.json`,
//! and embedded at compile time via `include_str!`.

use std::collections::HashMap;
use std::sync::Arc;

use crate::api_registry::{clear_api_providers, register_api_provider, ApiProvider};
use crate::providers::anthropic::{stream_anthropic, stream_simple_anthropic};
use crate::providers::openai::{stream_openai, stream_simple_openai};
use crate::providers::openai_responses::{stream_openai_responses, stream_simple_openai_responses};
use crate::providers::pi_messages::{stream_pi_messages, stream_simple_pi_messages};
use crate::types::Model;

/// Register all built-in API providers and default models.
pub fn register_built_in_api_providers() {
    load_generated_models();

    register_api_provider(
        ApiProvider {
            api: "anthropic-messages".to_string(),
            stream: Arc::new(move |model, context, options| {
                stream_anthropic(model, context, options)
            }),
            stream_simple: Arc::new(stream_simple_anthropic),
        },
        Some("builtin"),
    );

    register_api_provider(
        ApiProvider {
            api: "openai-completions".to_string(),
            stream: Arc::new(stream_openai),
            stream_simple: Arc::new(stream_simple_openai),
        },
        Some("builtin"),
    );

    register_api_provider(
        ApiProvider {
            api: "openai-responses".to_string(),
            stream: Arc::new(stream_openai_responses),
            stream_simple: Arc::new(stream_simple_openai_responses),
        },
        Some("builtin"),
    );

    register_api_provider(
        ApiProvider {
            api: "pi-messages".to_string(),
            stream: Arc::new(stream_pi_messages),
            stream_simple: Arc::new(stream_simple_pi_messages),
        },
        Some("builtin"),
    );

}

/// Clear all providers and re-register the built-in ones.
pub fn reset_api_providers() {
    clear_api_providers();
    register_built_in_api_providers();
}

/// Load models generated by `xtask` (`data/models_generated.json`), embedded at compile time.
fn load_generated_models() {
    let json = include_str!("../../data/models_generated.json");
    match serde_json::from_str::<HashMap<String, HashMap<String, Model>>>(json) {
        Ok(by_provider) => {
            for (_, models) in by_provider {
                for (_, model) in models {
                    crate::models::register_model(model);
                }
            }
        }
        Err(e) => {
            // data/models_generated.json 由 xtask 生成并提交进仓，编译期已嵌入。
            // 解析失败意味着产物与 Model 类型不一致，属于应当立刻暴露的 bug，
            // 不能静默注册 0 个模型（见 CLAUDE.md：禁止静默 fallback）。
            panic!("Failed to parse embedded data/models_generated.json: {e}");
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]
    use super::*;
    use crate::api_registry::get_api_provider;

    #[test]
    fn test_register_builtins_registers_anthropic() {
        register_built_in_api_providers();
        assert!(get_api_provider("anthropic-messages").is_some());
    }

    #[test]
    fn test_register_builtins_registers_openai() {
        register_built_in_api_providers();
        assert!(get_api_provider("openai-completions").is_some());
        assert!(get_api_provider("openai-responses").is_some());
    }

    #[test]
    fn test_register_builtins_registers_pi_messages() {
        register_built_in_api_providers();
        assert!(get_api_provider("pi-messages").is_some());
    }

    /// The generated catalog (from the original `generate-models.ts`) covers the
    /// full provider list, including providers whose models previously had no
    /// bundled catalog entry (e.g. `opencode-go`).
    #[test]
    fn test_generated_catalog_covers_full_provider_list() {
        register_built_in_api_providers();
        let providers = crate::models::get_providers();
        for provider in [
            "opencode-go",
            "opencode",
            "moonshotai",
            "moonshotai-cn",
            "xiaomi",
            "qwen-token-plan",
            "baseten",
            "huggingface",
            "cloudflare-workers-ai",
            "kimi-coding",
            "zai",
            "ant-ling",
        ] {
            assert!(
                providers.iter().any(|p| p == provider),
                "catalog should include {provider}"
            );
        }
        let opencode_go = crate::models::get_models("opencode-go");
        assert!(!opencode_go.is_empty(), "opencode-go should have models");
        for m in &opencode_go {
            assert!(
                matches!(
                    m.api.as_str(),
                    "openai-completions" | "anthropic-messages" | "openai-responses"
                ),
                "opencode-go/{} has unexpected api {}",
                m.id,
                m.api
            );
        }
    }


    /// `compat` is parsed according to the model's `api` (not via the untagged
    /// enum, which would always pick `OpenAICompletions` and drop the
    /// provider-specific fields).
    #[test]
    fn test_compat_parsed_by_api() {
        use crate::types::ModelCompat;
        let parse = |api: &str, compat: serde_json::Value| -> crate::types::Model {
            serde_json::from_value(serde_json::json!({
                "id": "m",
                "name": "m",
                "api": api,
                "provider": "p",
                "baseUrl": "https://example.com",
                "reasoning": true,
                "input": ["text"],
                "cost": { "input": 0.0, "output": 0.0 },
                "contextWindow": 1,
                "maxTokens": 1,
                "compat": compat,
            }))
            .unwrap()
        };

        let anthropic = parse(
            "anthropic-messages",
            serde_json::json!({"forceAdaptiveThinking": true, "supportsStrictTools": true}),
        );
        match anthropic.compat {
            Some(ModelCompat::AnthropicMessages(compat)) => {
                assert_eq!(compat.force_adaptive_thinking, Some(true));
                assert_eq!(compat.supports_strict_tools, Some(true));
            }
            other => panic!("anthropic compat parsed as {other:?}"),
        }

        let responses = parse(
            "openai-responses",
            serde_json::json!({"supportsStrictMode": true}),
        );
        match responses.compat {
            Some(ModelCompat::OpenAIResponses(compat)) => {
                assert_eq!(compat.supports_strict_mode, Some(true));
            }
            other => panic!("responses compat parsed as {other:?}"),
        }

        let completions = parse(
            "openai-completions",
            serde_json::json!({"thinkingFormat": "deepseek"}),
        );
        match completions.compat {
            Some(ModelCompat::OpenAICompletions(compat)) => {
                assert_eq!(compat.thinking_format.as_deref(), Some("deepseek"));
            }
            other => panic!("completions compat parsed as {other:?}"),
        }
    }

    #[test]
    fn test_reset_api_providers() {
        reset_api_providers();
        assert!(get_api_provider("anthropic-messages").is_some());
        assert!(get_api_provider("openai-completions").is_some());
        assert!(get_api_provider("openai-responses").is_some());
    }

    #[test]
    fn test_unknown_provider_returns_none() {
        register_built_in_api_providers();
        assert!(get_api_provider("unknown-api").is_none());
    }

    #[test]
    fn test_loads_generated_models() {
        register_built_in_api_providers();
        let providers = crate::models::get_providers();
        assert!(
            !providers.is_empty(),
            "Expected at least one provider from generated models, got none."
        );
    }
}
